# Generated by Django 4.2.7 on 2023-11-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_posts',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
