# Generated by Django 4.2.7 on 2023-11-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_related_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='related_posts',
        ),
    ]
